apiVersion: batch/v1
kind: Job
metadata:
  name: caed-perfis-permissoes-migrate
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: ghcr.io/ORGANIZACAO/caed-perfis-permissoes:TAG
          args: ["migrate"]
          envFrom:
            - configMapRef:
                name: caed-perfis-permissoes-config
            - secretRef:
                name: caed-perfis-permissoes-secrets
