apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: caed-perfis-permissoes-default
spec:
  podSelector:
    matchLabels:
      app: caed-perfis-permissoes
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 8000
  egress:
    - {}
