apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namePrefix: prod-
images:
  - name: ghcr.io/ORGANIZACAO/caed-perfis-permissoes
    newTag: production
patches:
  - target:
      kind: ConfigMap
      name: caed-perfis-permissoes-config
    patch: |-
      - op: add
        path: /data/APP_ENV
        value: production
