"""initial production schema

Revision ID: 8d23b5403827
Revises: 
Create Date: 2026-06-25 21:00:07.847751
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '8d23b5403827'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_settings_key'), ['key'], unique=True)

    op.create_table('approval_flow_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reviewer_name', sa.String(length=160), nullable=False),
    sa.Column('final_approver_name', sa.String(length=160), nullable=False),
    sa.Column('sla_hours', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=220), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_recipient'), ['recipient'], unique=False)

    op.create_table('organizational_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('responsible', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('organizational_units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizational_units_code'), ['code'], unique=True)

    op.create_table('process_specifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('correlation_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('responsible', sa.String(length=160), nullable=False),
    sa.Column('area', sa.String(length=160), nullable=False),
    sa.Column('source_document', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bizagi_case_id', sa.String(length=120), nullable=False),
    sa.Column('bizagi_sync_status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('process_specifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_process_specifications_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_process_specifications_correlation_id'), ['correlation_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_process_specifications_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_process_specifications_status'), ['status'], unique=False)

    op.create_table('role_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('permission_codes_json', sa.Text(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('role_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_definitions_name'), ['name'], unique=True)

    op.create_table('user_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_subject', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role_name', sa.String(length=120), nullable=False),
    sa.Column('unit_name', sa.String(length=180), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_accounts_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_accounts_external_subject'), ['external_subject'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_accounts_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_accounts_role_name'), ['role_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_accounts_status'), ['status'], unique=False)

    op.create_table('webhook_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('event_id', sa.String(length=160), nullable=False),
    sa.Column('payload_hash', sa.String(length=128), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'event_id', name='uq_webhook_provider_event')
    )
    with op.batch_alter_table('webhook_receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_receipts_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_receipts_provider'), ['provider'], unique=False)

    op.create_table('access_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('requested_role', sa.String(length=120), nullable=False),
    sa.Column('requested_permissions_json', sa.Text(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('assigned_to', sa.String(length=255), nullable=False),
    sa.Column('decision_by', sa.String(length=255), nullable=False),
    sa.Column('decision_note', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['process_id'], ['process_specifications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requester_id'], ['user_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('access_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_access_requests_process_id'), ['process_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_requests_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_access_requests_requester_id'), ['requester_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_requests_status'), ['status'], unique=False)

    op.create_table('approval_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('flow_id', sa.Integer(), nullable=True),
    sa.Column('stage_order', sa.Integer(), nullable=False),
    sa.Column('stage_name', sa.String(length=120), nullable=False),
    sa.Column('requested_by', sa.String(length=255), nullable=False),
    sa.Column('assigned_to', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('decision_by', sa.String(length=255), nullable=False),
    sa.Column('decision_note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['flow_id'], ['approval_flow_definitions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['process_id'], ['process_specifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_requests_process_id'), ['process_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_requests_status'), ['status'], unique=False)

    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('actor_email', sa.String(length=255), nullable=False),
    sa.Column('request_id', sa.String(length=80), nullable=False),
    sa.Column('ip_address', sa.String(length=80), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['process_specifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_process_id'), ['process_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_request_id'), ['request_id'], unique=False)

    op.create_table('integration_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('event_name', sa.String(length=100), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('correlation_id', sa.String(length=80), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('request_json', sa.Text(), nullable=False),
    sa.Column('response_json', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(length=120), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['process_specifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('integration_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integration_jobs_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_jobs_event_name'), ['event_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_jobs_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_integration_jobs_next_attempt_at'), ['next_attempt_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_jobs_process_id'), ['process_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_jobs_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_jobs_status'), ['status'], unique=False)

    op.create_table('profile_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('hierarchy', sa.String(length=120), nullable=False),
    sa.Column('profile_name', sa.String(length=220), nullable=False),
    sa.Column('agent_type', sa.String(length=220), nullable=False),
    sa.Column('permission_summary', sa.Text(), nullable=False),
    sa.Column('source_reference', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['process_specifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profile_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profile_definitions_process_id'), ['process_id'], unique=False)

    op.create_table('user_permission_grants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('permission_code', sa.String(length=120), nullable=False),
    sa.Column('granted_by', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['process_specifications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'process_id', 'permission_code', name='uq_user_process_permission')
    )
    with op.batch_alter_table('user_permission_grants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_permission_grants_permission_code'), ['permission_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_permission_grants_process_id'), ['process_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_permission_grants_user_id'), ['user_id'], unique=False)

    op.create_table('profile_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('permission_code', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'permission_code', name='uq_profile_permission')
    )
    with op.batch_alter_table('profile_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profile_permissions_profile_id'), ['profile_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profile_permissions_profile_id'))

    op.drop_table('profile_permissions')
    with op.batch_alter_table('user_permission_grants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_permission_grants_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_permission_grants_process_id'))
        batch_op.drop_index(batch_op.f('ix_user_permission_grants_permission_code'))

    op.drop_table('user_permission_grants')
    with op.batch_alter_table('profile_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profile_definitions_process_id'))

    op.drop_table('profile_definitions')
    with op.batch_alter_table('integration_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integration_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_integration_jobs_provider'))
        batch_op.drop_index(batch_op.f('ix_integration_jobs_process_id'))
        batch_op.drop_index(batch_op.f('ix_integration_jobs_next_attempt_at'))
        batch_op.drop_index(batch_op.f('ix_integration_jobs_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_integration_jobs_event_name'))
        batch_op.drop_index(batch_op.f('ix_integration_jobs_correlation_id'))

    op.drop_table('integration_jobs')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_request_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_process_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_events_category'))
        batch_op.drop_index(batch_op.f('ix_audit_events_action'))

    op.drop_table('audit_events')
    with op.batch_alter_table('approval_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_requests_status'))
        batch_op.drop_index(batch_op.f('ix_approval_requests_process_id'))

    op.drop_table('approval_requests')
    with op.batch_alter_table('access_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_requests_status'))
        batch_op.drop_index(batch_op.f('ix_access_requests_requester_id'))
        batch_op.drop_index(batch_op.f('ix_access_requests_public_id'))
        batch_op.drop_index(batch_op.f('ix_access_requests_process_id'))

    op.drop_table('access_requests')
    with op.batch_alter_table('webhook_receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_receipts_provider'))
        batch_op.drop_index(batch_op.f('ix_webhook_receipts_event_id'))

    op.drop_table('webhook_receipts')
    with op.batch_alter_table('user_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_accounts_status'))
        batch_op.drop_index(batch_op.f('ix_user_accounts_role_name'))
        batch_op.drop_index(batch_op.f('ix_user_accounts_name'))
        batch_op.drop_index(batch_op.f('ix_user_accounts_external_subject'))
        batch_op.drop_index(batch_op.f('ix_user_accounts_email'))

    op.drop_table('user_accounts')
    with op.batch_alter_table('role_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_definitions_name'))

    op.drop_table('role_definitions')
    with op.batch_alter_table('process_specifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_process_specifications_status'))
        batch_op.drop_index(batch_op.f('ix_process_specifications_public_id'))
        batch_op.drop_index(batch_op.f('ix_process_specifications_correlation_id'))
        batch_op.drop_index(batch_op.f('ix_process_specifications_code'))

    op.drop_table('process_specifications')
    with op.batch_alter_table('organizational_units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizational_units_code'))

    op.drop_table('organizational_units')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_recipient'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))

    op.drop_table('notifications')
    op.drop_table('approval_flow_definitions')
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_settings_key'))

    op.drop_table('app_settings')
    # ### end Alembic commands ###
